media:
  input: "_src/static/uploads"
  output: "/uploads"

content:
  - name: "settings"
    label: "Website settings"
    path: "config/_default/params.yml"
    type: file
    fields:
      - { name: "author", label: "Author", type: "string" }
      - { name: "description", label: "Description", type: "string" }
      - { name: "keywords", label: "Keywords", type: "string" }